[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x", "openssl"]

[phases.build]
cmds = ["npm install", "rm -rf dist", "npm run build", "npx prisma generate"]

[phases.start]
cmd = "npm start"

[variables]
PRISMA_QUERY_ENGINE_LIBRARY = "/app/node_modules/.prisma/client/libquery_engine-linux-musl-openssl-3.0.x.so.node"
