[phases.setup]
nixPkgs = ["nodejs-20_x", "npm-9_x", "openssl", "openssl_1_1"]

[phases.build]
cmds = ["npm install", "rm -rf dist", "npm run build", "npx prisma generate"]

[phases.start]
cmd = "npm start"
